
server:
  port: 5007

spring:
  application:
    name: payment-service
  jpa:
    hibernate:
      ddl-auto: update




  datasource:
    url: jdbc:mysql://localhost:3306/paymentdb_yt?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

spring.jpa.show-sql: true
  
razorpay:
  api:
   key: "your razorpay api key"
   secret: "your razorpay secret"
  
stripe:
  api:
    key: "your strip api key"

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/


